version: "3.5"
services:
  fabrial:
    image: fabrial:latest
    ports:
      - "6680:80"
    deploy:
      replicas: 1
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: fabrial_logs